export const defaultTheme = {
  colors: {
    white: '#fff',
    background: '#FAFAFA',
    card: '#F3F2F2',
    button: '#E6E5E5',
    hover: '#D7D5D5',
    label: '#8D8686',
    text: '#574F4D',
    subtitle: '#403937',
    title: '#272221',
    'purple-dark': '#4B2995',
    purple: '#8047F8',
    'purple-light': '#EBE5F9',
    'yellow-dark': '#C47F17',
    yellow: '#DBAC2C',
    'yellow-light': '#F1E9C9',
  },
  'text-sizes': {
    'title-xl': '3rem',
    'title-l': '2rem',
    'title-m': '1.5rem',
    'title-s': '1.2rem',
    'title-xs': '1.125rem',
    'text-regular-l': '1.25rem',
    'text-bold-l': '1.25rem',
    'text-regular-m': '1rem',
    'text-bold-m': '1rem',
    'text-regular-s': '0.875rem',
    'text-bold-s': '0.75rem',
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
}
